#!/usr/bin/tclsh

proc space20 {w} {
  upvar $w v
  set v [string map {{ } %20} $v]
}

foreach {i j} {
  BAW {British Airways} EIN {Aer Lingus} VIR {Virgin Atlantic} GFA {Gulf Air} UAE Emirates AIC {Air India}
  AFR {Air France} DLH Lufthansa IBE Iberia ELY {Israel Air} SHT {British Airways Shuttle} BMA {British Midland}
  TAM {TAM Brazilian} EZY EasyJet BCY CityJet ANZ {Air Newzealand} QFA Qantas SIA {Singapore Airlines} KAL {Korean Air}
  ACA {Air Canada} CTN {Croatia Airlines} AAL {American Airlines} UAL {United Airlines} COA {Continental Airlines} RYR {Ryan Air}
  TOM {Thomson Airways} KLM {Royal Dutch Airlines} SAS {Scandinavian Airlines} TCX {Thomas Cook} DAL {Delta Airlines} IWD {Orbest Airlines}
  AEE {Aegean Airlines} SLM {Surinam Airways} FIN {Fin Air} BMI {BMI Baby} TAP {Air Portugal} GMA {Gama Aviation} MOV {VIM Airlines}
  THY {Turkish Airlines} RZO {SATA International} TSC {Air Transat} SWR {Swiss Air} BEL {Brussels Airlines} MAU {Air Marutius}
  OMA {Oman Air} JAT {JAT Airways} KFR Kingfisher JAI {Jet Airways} CKS {Kalitta Air} IRA {Iran Air} EXS Jet2 AMC {Air Malta} MON {Monarch Airlines}
  AEU Astraeus MAS {Malaysian Airlines} AFL Aeroflot AWE {US Airways} SVA {Saudi Arabian Airlines} ALK {Srilankan Airlines} CPA {Cathay Pacific}
  TSO {Trans Aero} AZA Alitalia ROT Tarom IB3 Iberia MEA {Middle Eastern Airlines} QTR {Qatar Airways} PIA {Pakistan International}
  ICE {Iceland Air} SAA {South African Airways} ETH Ethiopian ETD Etihad CLX CargoLux CCA {Air China} AAR {Asiana Airlines} RBA {Royal Brunei Airlines}
  SEY {Air Seychelles} MSR {EgyptAir} THA {Thai Airways} EVA {Eva Air} AUA {Austrian Airlines} NAX {Norweigian Air Shuttle} KAC {Kuwait Airways} CYP {Cyprus Air} TUA {Turkmenistan Airlines}
  SYR {Syrian Airlines}
} {set airline($i) $j}


set flightnum [lindex $argv 0]
set icao [lindex $argv 1]
set reg [string trim [lindex $argv 2]]
set type [lindex $argv 3]
set alt "[lindex $argv 4] ft"
set intent "[lrange $argv 5 7] ft"

foreach i {alt intent} {space20 $i}

  set fd [open out w]


  set html [exec curl http://data.flight24.com/airplanes/$reg/ 2> err]
  set today [clock format [clock seconds] -format "%Y-%m-%d"]
  set start [string first @ $html]; incr start
  set end [string first CET $html]; incr end -1
  set day [string range [string trim [string range $html $start $end]] 0 [expr [string length $today] - 1]]
  if {$today ne $day} {
    set from unknown
    set to unknown
    set flight [string range [lindex $argv 0] 0 2]
    if { [array names airline -exact $flight] ne "" } {
      set caller $airline($flight)
    } else {
      set caller unknown
    }


    puts $fd "unknown\nunknown\n$caller"
    space20 caller
    set poster "http://manurevah.com/lhr/flight_post.php?flight=$flightnum&icao=$icao&regn=$reg&from=$from&to=$to&type=$type&airline=$caller&alt=$alt&intent=$intent"
    exec curl $poster >& err
    return
  }

  set start [string first {route from} $html]
  set html [string range $html $start end]

  foreach i {from to} {
    set needle title="
    set start [string first $needle $html]
    incr start [string length $needle]
    set html [string range $html $start end]
    set end [string first {"} $html]
    incr end -1
    set result [string trim [string range $html 0 $end]]
    puts $fd $result
    set $i $result
  }

  set flight [string range [lindex $argv 0] 0 2]
  if { [array names airline -exact $flight] ne "" } {
    set caller $airline($flight)
  } else {
    set caller unknown
  }

  puts $fd $caller

  space20 from
  space20 to
  space20 caller

  set poster "http://manurevah.com/lhr/flight_post.php?flight=$flightnum&icao=$icao&regn=$reg&from=$from&to=$to&type=$type&airline=$caller&alt=$alt&intent=$intent"
  exec curl $poster >& err


