#!/usr/bin/tclsh

proc space20 {w} {
  upvar $w v
  set v [string map {{ } %20} $v]
}

foreach {i j} {
  BAW {British Airways} EIN {Aer Lingus} VIR {Virgin Atlantic} GFA {Gulf Air} UAE Emirates AIC {Air India}
  AFR {Air France} DLH Lufthansa IBE Iberia ELY {El Al} SHT {British Airways Shuttle} BMA {British Midland}
  TAM {TAM Airlines} EZY easyJet BCY CityJet ANZ {Air Newzealand} QFA Qantas SIA {Singapore Airlines} KAL {Korean Air}
  ACA {Air Canada} CTN {Croatia Airlines} AAL {American Airlines} UAL {United Airlines} COA {Continental Airlines} RYR {Ryanair}
  TOM {Thomson Airways} KLM KLM SAS {Scandinavian Airlines} TCX {Thomas Cook Airlines} DAL {Delta Airlines} IWD {Orbest Airlines}
  AEE {Aegean Airlines} SLM {Surinam Airways} FIN Finnair BMI bmibaby TAP {Air Portugal} GMA {Gama Aviation} MOV {VIM Airlines}
  THY {Turkish Airlines} RZO {SATA International} TSC {Air Transat} SWR Swissair BEL {Brussels Airlines} MAU {Air Marutius}
  OMA {Oman Air} JAT {JAT Airways} KFR {Kingfisher Airlines} JAI {Jet Airways} CKS {Kalitta Air} IRA {Iran Air} EXS Jet2 AMC {Air Malta} MON {Monarch Airlines}
  AEU {Astraeus Airlines} MAS {Malaysian Airlines} AFL Aeroflot AWE {US Airways} SVA {Saudi Arabian Airlines} ALK {Srilankan Airlines} CPA {Cathay Pacific}
  TSO {Transaero Airlines} AZA Alitalia ROT Tarom IB3 Iberia MEA {Middle Eastern Airlines} QTR {Qatar Airways} PIA {Pakistan International}
  ICE {Iceland Air} SAA {South African Airways} ETH Ethiopian ETD {Etihad Airways} CLX CargoLux CCA {Air China} AAR {Asiana Airlines} RBA {Royal Brunei Airlines}
  SEY {Air Seychelles} MSR {Egyptair} THA {Thai Airways} EVA {Eva Air} AUA {Austrian Airlines} NAX {Norweigian Air Shuttle} KAC {Kuwait Airways} CYP {Cyprus Air} TUA {Turkmenistan Airlines}
  SYR {Syrian Airlines} VLG {Vueling Airlines} CAL {China Airlines} TAR {Tunis Air} ANA {All Nippon Airways} KQA {Keynya Airways} LOT {LOT - Polish Airlines}
  WZZ {Wizz Air} DAH {Air Algerie} BBC {Biman Bangladesh} MNG {MNG Cargo} RAM {Royal Air Maroc} JAL {Japan Airlines} RJA {Royal Jordanian Airlines} FDX FedEx ARA {Arik Air}
  ATN {Air Transport International} UA {United Airlines} CES {China Eastern Airlines} UZB {Uzbekistan Airways} AHY {Azerbaijan Airlines} LZB {Bulgaria Air} UPS {United Parcel Services}
} {set airline($i) $j}


set flightnum [lindex $argv 0]
set icao [lindex $argv 1]
set reg [string trim [lindex $argv 2]]
set type [lindex $argv 3]
set itinerary [lindex $argv 4]
set lat [lindex $argv 5]
set lon [lindex $argv 6]
set alt "[lindex $argv 7] ft"
set intent "[lrange $argv 8 10] ft"

foreach i {alt intent} {space20 $i}

  set fd [open out w]

  if {$itinerary eq 1} {

    set html [exec curl http://data.flight24.com/airplanes/$reg/ --connect-timeout 10 2> err]

    set start [string first {route from} $html]
    set html [string range $html $start end]

    foreach i {from to} {
      set needle title="
      set start [string first $needle $html]
      incr start [string length $needle]
      set html [string range $html $start end]
      set end [string first {"} $html]
      incr end -1
      set result [string trim [string range $html 0 $end]]
      puts $fd $result
      set $i $result
    }

    set flight [string range [lindex $argv 0] 0 2]
    if { [array names airline -exact $flight] ne "" } {
      set caller $airline($flight)
    } else {
      set caller unknown
    }

    puts $fd $caller
    close $fd

    space20 from
    space20 to
    space20 caller

    set poster "http://manurevah.com/lhr/flight_post.php?icao=$icao&flight=$flightnum&regn=$reg&from=$from&to=$to&type=$type&airline=$caller&alt=$alt&intent=$intent&lat=$lat&lon=$lon"

  } else {
    set poster "http://manurevah.com/lhr/flight_post.php?&icao=$icao&alt=$alt&intent=$intent&lat=$lat&lon=$lon"
  }

  exec curl $poster >& err &
